### ISSUE TITLE
WASM Compatibility? 

### ISSUE THREAD

**Issue by novacrazy** [inflation/jpegxl-rs#14]
I have not tested it yet, but would it be feasible to compile this library and the dependencies to WASM? 

Google Chrome seems intent to fully drop support for JPEG XL and Firefox never really enabled it either, so it looks like a WASM module is the only way forward to use it on a website.

**Comment by inflation** [comment]
I could build it using:

```rust
cargo build --target=wasm32-unknown-emscripten --no-default-features -F vendored
```

But somehow `cargo test` failed on `Permission denied` and manually run the JS file resulted in not finding the test image files, so I didn't test it. You're welcome to try it, and I'm eagerly awaiting any feedbacks.

**Comment by novacrazy** [comment]
Given this project is GPLv3, that makes actually using it kind of tricky. Would a WASM module be considered "dynamic linking" enough to use this library in a non-GPLv3 frontend? If not that, then perhaps an isolated WebWorker that only communicates with the main application through JSON/ArrayBuffers?
