### ISSUE TITLE
Parallelism

### ISSUE THREAD

**Issue by cavemanloverboy** [inflation/jpegxl-rs#15]
I'm trying to encode a large image via

```rust
let parallel = ThreadsRunner::new(None, Some(48)).unwrap();
let mut encoder = encoder_builder()
    .has_alpha(false)
    .lossless(true)
    .speed(EncoderSpeed::Tortoise)
    .parallel_runner(&parallel)
    .build()
    .expect("failed to build encoder");
let mut buffer: EncoderResult<u8> = encoder
    .encode(&big_image, 20_000, 20_000)
    .expect("failed to encode image");
```
on a machine with 48 threads but I only see ≈100% CPU utilization (one thread) via `top`:
```
    PID USER      PR  NI    VIRT    RES    SHR S  %CPU  %MEM     TIME+ COMMAND          
2555019 cavey     20   0   30.9g  25.0g  11556 S 100.3   5.0  40:37.76 compress
```
am I doing something wrong?

**Comment by inflation** [comment]
You could check how many threads does the process spawned. `ThreadsRunner` is a simple thread pool, so it should spawn the threads beforehand. 

My guess is the lossless mode, since it's using another algorithm under the hood, and not much optimized upstream, unfortunately.

**Comment by cavemanloverboy** [comment]
I tried removing `lossless` and used non-tortoise mode and I still seem to be getting only one thread

**Comment by inflation** [comment]
Then maybe it's just not optimized well. I could get about 400% utilization on 11 threads in benchmarking. Decoding is much better at 800%.
