### ISSUE TITLE
Building with vendored is extremely slow

### ISSUE THREAD

**Issue by Kl4rry** [inflation/jpegxl-rs#17]
I tried building the library with the vendored flag on a cpu with 32 threads and the building of the sys crate is not even using a single whole thread. Should it not use more threads as the `CMAKE_BUILD_PARALLEL_LEVEL` is set to the number of CPU threads? I don't know how long it actually takes to build it but it is atleast 30 minutes.

cpu: ryzen 5950x
os: windows

**Comment by inflation** [comment]
I have set `CMAKE_BUILD_PARALLEL_LEVEL` to `std::thread::available_parallelism()` when building. And I can confirm it works on Linux and macOS. Maybe something wrong about Windows? Have you tried to build `libjxl` itself?

**Comment by inflation** [comment]
> I tried hard coding the core count to 32 but it made no difference. I even let it compile for multiple hours and it did not finish. There is something very weird going on with windows compilation. I am going to try to compile just libjxl when i get time.

Yes, someone said it hangs on Windows in the other issue.
