### ISSUE TITLE
#0 8.968   failed to verify the checksum of `jpegxl-rs v0.8.1+libjxl-0.8.1`

### ISSUE THREAD

**Issue by xxai-arter** [inflation/jpegxl-rs#20]
#0 8.968   failed to verify the checksum of `jpegxl-rs v0.8.1+libjxl-0.8.1`

use 0.8.0 is ok
<img width="469" alt="image" src="https://user-images.githubusercontent.com/130081562/230565868-15c54136-a4f4-4af5-b297-b930e73c4164.png">

**Comment by inflation** [comment]
Just tried and it works fine. Maybe clear the cache and try again?

**Comment by wacdev** [comment]
<img width="1858" alt="image" src="https://user-images.githubusercontent.com/127726508/230599073-8fe45ac8-5ec0-4cea-8181-1f3c7729b4bd.png">

I use docker with alpine , everytime this error, I lock version to 0.8.0 then ok

**Comment by wacdev** [comment]
<img width="1920" alt="image" src="https://user-images.githubusercontent.com/127726508/230599339-64c70d6f-4a44-44f9-9836-d66239141632.png">

when I try to enable vendored, in docker alpine this error happend
```

#0 89.79   [ 82%] Built target jxl_dec-obj
#0 89.79
#0 89.79   --- stderr
#0 89.79   Warning: HWY_SVE, HWY_SVE2, HWY_SVE_256, HWY_SVE2_128 and HWY_RVV CPU targets are disabled
#0 89.79   CMake Deprecation Warning at third_party/brotli/CMakeLists.txt:5 (cmake_minimum_required):
#0 89.79     Compatibility with CMake < 2.8.12 will be removed from a future version of
#0 89.79     CMake.
#0 89.79
#0 89.79     Update the VERSION argument <min> value or use a ...<max> suffix to tell
#0 89.79     CMake that the project does not need compatibility with older versions.
#0 89.79
#0 89.79
#0 89.79   -- Compiler is not EMSCRIPTEN
#0 89.79   CMake Warning:
#0 89.79     Manually-specified variables were not used by the project:
#0 89.79
#0 89.79       CMAKE_ASM_COMPILER
#0 89.79       CMAKE_ASM_FLAGS
#0 89.79
#0 89.79
#0 89.79   make: warning: -j6 forced in submake: resetting jobserver mode.
#0 89.79   Config: emu128:0 scalar:0 static:0 all_attain:0 is_test:0
#0 89.79   Compiled HWY_TARGETS:   NEON
#0 89.79   HWY_ATTAINABLE_TARGETS: NEON SCALAR
#0 89.79   HWY_BASELINE_TARGETS:   NEON SCALAR
#0 89.79   HWY_STATIC_TARGET:      NEON
#0 89.79   HWY_BROKEN_TARGETS:
#0 89.79   HWY_DISABLED_TARGETS:   SVE2_128 SVE_256 SVE2 SVE Unknown
#0 89.79   Current CPU supports:   NEON EMU128 SCALAR
#0 89.79   /usr/lib/gcc/aarch64-alpine-linux-musl/10.3.1/../../../../aarch64-alpine-linux-musl/bin/ld: attempted static link of dynamic object `libbrotlicommon.so.1.0.7'
#0 89.79   collect2: error: ld returned 1 exit status
#0 89.79   make[2]: *** [third_party/brotli/CMakeFiles/brotlienc.dir/build.make:370: third_party/brotli/libbrotlienc.so.1.0.7] Error 1
#0 89.79   make[1]: *** [CMakeFiles/Makefile2:412: third_party/brotli/CMakeFiles/brotlienc.dir/all] Error 2
#0 89.79   make[1]: *** Waiting for unfinished jobs....
#0 89.79   make: *** [Makefile:146: all] Error 2
#0 89.79   thread 'main' panicked at '
#0 89.79   command did not execute successfully, got: exit status: 2
#0 89.79
#0 89.79   build script failed, must exit now', /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/cmake-0.1.50/src/lib.rs:1098:5
#0 89.79   note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
#0 89.79 warning: build failed, waiting for other jobs to finish...
------
ERROR: failed to solve: executor failed running [/bin/sh -c source $HOME/.cargo/env &&   sed -i '/^jpegxl-rs/s/^/# /' Cargo.toml &&  echo -e "\n[dependencies.jpegxl-rs]\nversion=\"=0.8.0\"\nfeatures=[\"vendored\
"]\n[dependencies.jpegxl-sys]\nversion=\"=0.8.0\"" >> Cargo.toml &&  ./dist.sh]: exit code: 101
```

**Comment by inflation** [comment]
@wacdev This is a different issue. Let's discuss it in another place.

**Comment by wacdev** [comment]
> #0 89.79   [ 82%] Built target jxl_dec-obj
> #0 89.79
> #0 89.79   --- stderr
> #0 89.79   Warning: HWY_SVE, HWY_SVE2, HWY_SVE_256, HWY_SVE2_128 and HWY_RVV CPU targets are disabled
> #0 89.79   CMake Deprecation Warning at third_party/brotli/CMakeLists.txt:5 (cmake_minimum_required):
> #0 89.79     Compatibility with CMake < 2.8.12 will be removed from a future version of
> #0 89.79     CMake.
> #0 89.79
> #0 89.79     Update the VERSION argument <min> value or use a ...<max> suffix to tell
> #0 89.79     CMake that the project does not need compatibility with older versions.
> #0 89.79
> #0 89.79
> #0 89.79   -- Compiler is not EMSCRIPTEN
> #0 89.79   CMake Warning:
> #0 89.79     Manually-specified variables were not used by the project:
> #0 89.79
> #0 89.79       CMAKE_ASM_COMPILER
> #0 89.79       CMAKE_ASM_FLAGS
> #0 89.79
> #0 89.79
> #0 89.79   make: warning: -j6 forced in submake: resetting jobserver mode.
> #0 89.79   Config: emu128:0 scalar:0 static:0 all_attain:0 is_test:0
> #0 89.79   Compiled HWY_TARGETS:   NEON
> #0 89.79   HWY_ATTAINABLE_TARGETS: NEON SCALAR
> #0 89.79   HWY_BASELINE_TARGETS:   NEON SCALAR
> #0 89.79   HWY_STATIC_TARGET:      NEON
> #0 89.79   HWY_BROKEN_TARGETS:
> #0 89.79   HWY_DISABLED_TARGETS:   SVE2_128 SVE_256 SVE2 SVE Unknown
> #0 89.79   Current CPU supports:   NEON EMU128 SCALAR
> #0 89.79   /usr/lib/gcc/aarch64-alpine-linux-musl/10.3.1/../../../../aarch64-alpine-linux-musl/bin/ld: attempted static link of dynamic object `libbrotlicommon.so.1.0.7'
> #0 89.79   collect2: error: ld returned 1 exit status
> #0 89.79   make[2]: *** [third_party/brotli/CMakeFiles/brotlienc.dir/build.make:370: third_party/brotli/libbrotlienc.so.1.0.7] Error 1
> #0 89.79   make[1]: *** [CMakeFiles/Makefile2:412: third_party/brotli/CMakeFiles/brotlienc.dir/all] Error 2
> #0 89.79   make[1]: *** Waiting for unfinished jobs....
> #0 89.79   make: *** [Makefile:146: all] Error 2
> #0 89.79   thread 'main' panicked at '
> #0 89.79   command did not execute successfully, got: exit status: 2
> #0 89.79
> #0 89.79   build script failed, must exit now', /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/cmake-0.1.50/src/lib.rs:1098:5
> #0 89.79   note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
> #0 89.79 warning: build failed, waiting for other jobs to finish...
> ------
> ERROR: failed to solve: executor failed running [/bin/sh -c source $HOME/.cargo/env &&   sed -i '/^jpegxl-rs/s/^/# /' Cargo.toml &&  echo -e "\n[dependencies.jpegxl-rs]\nversion=\"=0.8.0\"\nfeatures=[\"vendored\
> "]\n[dependencies.jpegxl-sys]\nversion=\"=0.8.0\"" >> Cargo.toml &&  ./dist.sh]: exit code: 101

see https://github.com/inflation/jpegxl-rs/issues/21

```
git clone [git@github.com](mailto:git@github.com):wacdev/rust.git
./rust/img/docker.build.sh
```


and remove  
``` echo -e "\n[dependencies.jpegxl-rs]\nversion=\"=0.8.0\"\nfeatures=[\"vendored\"]\n[dependencies.jpegxl-sys]\nversion=\"=0.8.0\"" >> Cargo.toml &&\
```
is Dockerfile
will see checksum error

**Comment by wacdev** [comment]
code https://github.com/wacdev/rust/commit/01e76103cb62cfac37ba57b506d4597807d46893

github action error there https://github.com/wacdev/rust/actions/runs/4642933500/jobs/8217234357

<img width="1046" alt="image" src="https://user-images.githubusercontent.com/127726508/230700403-8f9b9645-75ac-4ab9-8bba-da2d14391a5c.png">

**Comment by inflation** [comment]
> failed to download replaced source registry `crates-io`

Are you using a mirror?

**Comment by wacdev** [comment]
not use mirror

**Comment by inflation** [comment]
I guess this could be related to the GitHub checksum change. Just tried with a new version `0.8.2-alpha` and it works on Linux. Please see if this solves the issue.

**Comment by GageBerz** [comment]
#[7180](https://github.com/rust-lang/cargo/issues/7180)
