### ISSUE TITLE
how to encode vec<u8> ?

### ISSUE THREAD

**Issue by wacdev** [inflation/jpegxl-rs#22]
I try this code, the avif and webp encode right ,but jpge-xl encode `ERR: The encoder API is used in an incorrect way`

```
    match ext {
      // https://github.com/kornelski/cavif-rs --speed=n — Encoding speed between 1 (best, but slowest) and 10 (fastest, but a blurry mess), the default value is 4. Speeds 1 and 2 are unbeli
  evably slow, but make files ~3-5% smaller. Speeds 7 and above degrade compression significantly, and are not recommended.
      Ext::avif => AvifEncoder::new_with_speed_quality(&mut result_buf, 5, 64).write_image(
        img,
        width,
        height,
        ColorType::Rgba8,
      )?,
      Ext::webp => WebPEncoder::new_with_quality(&mut result_buf, WebPQuality::lossy(82))
        .write_image(img, width, height, ColorType::Rgba8)?,
      Ext::jxl => {
        use image::{DynamicImage, ImageBuffer, Rgba};
        use jpegxl_rs::{
          encode::{EncoderResult, EncoderSpeed},
          encoder_builder,
        };
        let img = DynamicImage::ImageRgba8(
          ImageBuffer::<Rgba<u8>, Vec<u8>>::from_raw(width, height, img.into()).unwrap(),
        );

        let mut encoder = encoder_builder()
          .quality(3.0)
          .speed(EncoderSpeed::Kitten)
          .build()?;
        let buffer: EncoderResult<f32> = encoder.encode(&img.to_rgba16(), width, height)?;
        return Ok(Some(buffer.data));
      }
    };
```

<img width="1907" alt="image" src="https://user-images.githubusercontent.com/127726508/231048865-413d1bf7-2b5e-4437-b5b6-e6723d3d81e5.png">

**Comment by inflation** [comment]
You need to set number of channels explicitly, by default it's RGB without alpha channel.

**Comment by wacdev** [comment]
I use to_rgb() then success

this doc maybe need update ( the code use to_rgba16 maybe not right) 
https://docs.rs/jpegxl-rs/latest/jpegxl_rs/#encoding

<img width="1017" alt="image" src="https://user-images.githubusercontent.com/127726508/231331151-2e7bebc5-66c3-4b5d-b854-14fd0b85acfd.png">

**Comment by inflation** [comment]
There is a note on `encode` function stating that. `has_alpha` means the _output_ image has alpha channel. Input frame settings should be set in `add_frame` function.

**Comment by inflation** [comment]
I did run doc test when doing release, so that's strange and I need to investigate more. 

I guess I'd add more convenient functions with `image` integrations to streamline the process.
