### ISSUE TITLE
Can't build staticly with vendored feature

### ISSUE THREAD

**Issue by SalOne22** [inflation/jpegxl-rs#30]
How to static build for `x86_64-pc-windows-msvc` target?

Currently have issues with `vendored` feature, because libjxl can not be build with msvc compiler. So I build libjxl with vcpkg (uses clang) and use DEP_LIB_JXL for linking, but when i test this build on windows vm, jxl.dll and jxl_threads.dll cant be found. 
Do you have options to enable `vendored` feature without building the library?

**Comment by inflation** [comment]
No there isn't. However, you could overwrite any `cmake` options like the instructions in `libjxl` repo.
