### ISSUE TITLE
Images missing from sys crate

### ISSUE THREAD

**Issue by werdahias** [inflation/jpegxl-rs#34]
The sys crate when pulled from crate.io does not contain the test images so the tests naturally fail to run. Please consider including them in the uploads.

**Comment by inflation** [comment]
Umm. What's the usage of this? All samples are stored in the parent repo to share with multiple crates. And its solely purpose is for development.

**Comment by werdahias** [comment]
I package rust crates for debian and we usually run the tests. having the testdata not available fails the tests which is not good

**Comment by werdahias** [comment]
I guess I could, but this would produce extra churn.
