### ISSUE TITLE
Non-transparent images are decoded incorrectly

### ISSUE THREAD

**Issue by anongit** [inflation/jpegxl-rs#4]
The `convert` and `stream` utils are from ImageMagick.

Steps to reproduce:
```sh
convert test/sample.png -alpha off test/sample.png
cjxl -q 100 test/sample.{png,jxl}
cargo test 'image::tests::test_image_support' | head -c 350
```
The output:
```test
running 1 test
test image::tests::test_image_support ... FAILED

failures:

---- image::tests::test_image_support stdout ----
thread 'image::tests::test_image_support' panicked at 'assertion failed: `(left == right)`
  left: `None`,
 right: `Some(ImageBuffer { width: 2122, height: 1433, _phantom: PhantomData, data: [253, 249, 230, 253, 249, 230, 2
```

With the following patch:
```diff
diff --git a/src/image.rs b/src/image.rs
index 04cd87d..e1cd724 100644
--- a/src/image.rs
+++ b/src/image.rs
@@ -135,6 +135,7 @@ mod tests {
         let img = image::DynamicImage::from_decoder(decoder)?;
         let sample_png = image::io::Reader::open("test/sample.png")?.decode()?;
 
+        img.save("./sample.jxl.png")?;
         assert_eq!(img.as_rgb8(), sample_png.as_rgb8());
 
         Ok(())
```
The `sample.jxl.png` file looks like this:

![sample](https://user-images.githubusercontent.com/3994490/114656381-6634cb80-9d07-11eb-96eb-1a12822d39e8.jpg)

The data is treated as an RGB image, but there are extra alpha values in it:
```sh
file ./sample.jxl.png
# ./sample.jxl.png: PNG image data, 2122 x 1433, 16-bit/color RGB, non-interlaced

stream ./sample.jxl.png - | xxd -l 12 -g 4
# 00000000: fdf9e6ff fdf9e6ff fdf9e6ff           ............

stream ./test/sample.png - | xxd -l 9 -g 3
# 00000000: fdf9e6 fdf9e6 fdf9e6                   .........
```

The following patch fixes the problem for me:
```diff
diff --git a/src/decode.rs b/src/decode.rs
index 5f1fb92..b913d80 100644
--- a/src/decode.rs
+++ b/src/decode.rs
@@ -318,7 +318,11 @@ impl<'a> JxlDecoder<'a> {
             format.assume_init()
         };
 
-        let num_channels = self.options.num_channels.unwrap_or(format.num_channels);
+        let num_channels = self.options.num_channels.unwrap_or(match basic_info {
+            Some(JxlBasicInfo { alpha_bits: 0, .. }) => 3,
+            _ => format.num_channels, // hardcoded as 4 in JxlDecoderDefaultPixelFormat
+        });
+
         let endianness = self.options.endianness.unwrap_or(format.endianness);
         let align = self.options.align.unwrap_or(format.align);
 
diff --git a/src/image.rs b/src/image.rs
index 04cd87d..956f9dd 100644
--- a/src/image.rs
+++ b/src/image.rs
@@ -135,8 +135,34 @@ mod tests {
         let img = image::DynamicImage::from_decoder(decoder)?;
         let sample_png = image::io::Reader::open("test/sample.png")?.decode()?;
 
+        // For any non rgb8 images, e.g. rgba8/16:
+        assert_eq!(img.as_rgb8(), None);
+        assert_eq!(sample_png.as_rgb8(), None);
+
+        // So this is just assert_eq!(None, None):
         assert_eq!(img.as_rgb8(), sample_png.as_rgb8());
 
+        // The assert below works for both rgb8 and rgba8 samples,
+        // assuming JxlImageDecoder<u8> is used.
+        //
+        // With JxlImageDecoder<u16> one needs to convert to rgba8/16 first.
+        //
+        // Using into_rgba16() doesn't quite work, because djxl and image-rs
+        // use different conversion methods.
+        //
+        // image-rs basically does:
+        // rgba[i] *= 256
+        //
+        // djxl converts to float 0..1 and scales by (1 << bits_per_sample) - 1
+        // or u16::MAX in this case:
+        // rgba[i] = rgba[i] / 255 * 65535
+        //
+        // into_rgba8() should be fine as long as the original image is 8-bit.
+        let img = img.into_rgba8();
+        let sample_png = sample_png.into_rgba8();
+
+        assert_eq!(img, sample_png);
+
         Ok(())
     }
 }
```
The current `test/sample.jxl` doesn't pass the test. I imagine that it was lossy encoded to reduce the space and `assert_eq!` was a no op, so the test passed, but the image needs to be losslessly encoded to match the original.
As a side note, why not use smaller test images like `50 x 50`? Less repo space, faster test runs and asserts don't wipe the screen with failed comparisons.

**Comment by inflation** [comment]
Ah, the samples are encoded with previous versions, maybe something changed along the way. I'll look into it.

As for the image size, the samples are also used in benchmarks, so I don't bother to use another one. Maybe you are right.

**Comment by anongit** [comment]
My problem is that I don't know how many channels the input image has, e.g. an image viewer tries to open a random file.
How can I get this info with `JxlDecoder` or otherwise?

**Comment by inflation** [comment]
`PixelFormat` sets the _output_ format. The underlying decoder solves the input format by itself. Therefore, by default, it preserves the alpha channel even if the source doesn't have one. I tested the image without the alpha channel with default settings, e.g., `num_channels: 4`, simply discarding the alpha channel results in the same pixels as the original.

So in practice, you don't need to know that. Set the number of channels to match your need. But if you really need to know that info, you can check the `has_alpha` value in the returned `ResultInfo` along with the pixels.

**Comment by anongit** [comment]
I see. So I guess the issue here is that `JxlImageDecoder::color_type()` relies on `has_alpha` to determine if an image is RGB or RGBA but the output is always RGBA and this messes with whatever `image` crate does later.
