### ISSUE TITLE
Can't encode image. Generic Error("Add Frame").

### ISSUE THREAD

**Issue by lucassith** [inflation/jpegxl-rs#8]
Encoding the image the same way as shown in the example gives me an error - Generic Error("Add Frame"). I am using the system's library with system-jxl feature but adding DEP_JXL_INCLUDE and DEP_JXL_LIB throws an error about missing libjxl.so.0 while setting LD_LIBRARY_PATH solves it.

**Comment by inflation** [comment]
If you are using the system library, the internal debug info is suppressed by default. You need to compile it in debug mode (`cargo build` implies this to `cmake`).
