### ISSUE TITLE
Encoding a RGBA png produces a garbled output.

### ISSUE THREAD

**Issue by jindalpratik** [inflation/jpegxl-rs#96]
Converting the following sample image whose sample.color() shows as Rgba16:
![sample](https://github.com/user-attachments/assets/8ac78cb1-cb11-4b25-81b1-9e42312bc107)
with the following code 
```
    let sample = ImageReader::open("./sample.png")
        .unwrap()
        .decode()
        .unwrap();

    println!("{:?}", sample.color());

    // Set encoder options
    let mut encoder = encoder_builder()
        .lossless(true)
        .uses_original_profile(true)
        .speed(EncoderSpeed::Squirrel)
        .build()
        .unwrap();

    let buffer: EncoderResult<f32> = encoder
        .encode(&sample.to_rgba16(), sample.width(), sample.height())
        .unwrap();

    fs::write("./smple.jxl", `buffer.as_ref()).unwrap();
```
produces the following garbled image: (uploading a screenshot as github doesn't allow jxl images)
![image](https://github.com/user-attachments/assets/9f44398f-be82-41ab-b373-4b8ca644df0f)

while encoding the same image as rgb16 works fine and produces the following image:
```
    let buffer: EncoderResult<f32> = encoder
        .encode(&sample.to_rgb16(), sample.width(), sample.height())
        .unwrap();

    fs::write("./smple.jxl", buffer.as_ref()).unwrap();
```
![image](https://github.com/user-attachments/assets/33f3a84c-0190-4d3b-a15e-2ef029cd1021).

I still trying to figure stuff out so I might be doing something wrong but I am unable to convert any image with an alpha channel while keeping the alpha channel and any help in this matter is really appreciated.

Tried on 
jpegxl-rs = { version = "0.11.0", features = ["vendored"] } and
jpegxl-rs = { version = "0.10.4", features = ["vendored"] }

**Comment by inflation** [comment]
To add an alpha channel, you need to create an `EncoderFrame` manually, and set the number of channels [there](https://docs.rs/jpegxl-rs/0.10.4+libjxl-0.10.3/jpegxl_rs/encode/struct.EncoderFrame.html#method.num_channels).

**Comment by jindalpratik** [comment]
Thanks a lot that worked.
